dasharo-compatibility/306-usb-hid-and-msc-support.md: update description tests USB001.003 and USB002.003
Dasharo/docs pull request #172
Opened 2022-04-28 14:09 UTC by Pokisiekk

Signed-off-by: Kamil Pokornicki <kamil.pokornicki@3mdeb.com>

2022-04-29 10:34 UTC, sulewskiprzemyslaw requested changes

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Informations about connected keyboard should be displayed.
```suggestion
1. Information about connected keyboard should be displayed.
```

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Connect additional USB device, run command once again and note reults.
```suggestion
Connect additional USB device, run command once again and note the results.
```

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Example output:
Indentation missing

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +1. Note results.
```suggestion
1. Note the results.
```

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Connect additional USB device, run command once again and note reults.
indentation missing

2022-04-29 10:34 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Informations about connected keyboard should be displayed.
indentation missing

2022-04-29 10:58 UTC, Pokisiekk commented on docs/unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
> +Informations about connected keyboard should be displayed.
add all improvements

2022-05-04 07:09 UTC, sulewskiprzemyslaw approved these changes

2022-05-04 07:37 UTC, merged