audio subsystem automation
Dasharo/docs pull request #195
Opened 2022-05-24 07:48 UTC by PrzemyslawBanasiak13

Signed off by Przemysław Banasiak (przemyslaw.banasiak@3mdeb.com)

2022-05-31 08:00 UTC, sulewskiprzemyslaw requested changes

2022-05-31 08:00 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
> +1. External headset should be listed in the output.
In think, that in section `Expected result` we should add output example

2022-06-02 06:41 UTC, sulewskiprzemyslaw requested changes

2022-06-02 06:41 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
> +1. Proceed with the Common section.
Why this hyperlink has been erased?

2022-06-02 06:55 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
> +1. Proceed with the Common section.
Deleted accidentally

2022-06-02 06:56 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
> +1. Proceed with the Common section.
```suggestion
1. Proceed with the [Common](#common) section.
```

2022-06-02 08:00 UTC, sulewskiprzemyslaw approved these changes

2022-06-02 08:13 UTC, merged