add tests for win11 cpu status
Dasharo/docs pull request #227
Opened 2022-06-23 10:52 UTC by PrzemyslawBanasiak13

Signed-off-by: pbanasiak <przemyslaw.banasiak@3mdeb.com>

2022-06-23 14:14 UTC, sulewskiprzemyslaw requested changes

2022-06-24 07:19 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> +```powershell
Done

2022-06-24 07:19 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> +```bash
Done

2022-06-24 07:19 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> +```bash
Done

2022-06-24 07:20 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> +```powershell
Done

2022-06-24 11:13 UTC, sulewskiprzemyslaw approved these changes

2022-07-13 11:22 UTC, macpijan commented
@sulewskiprzemyslaw Whi is this not merged still, if approved?
I can see we have pre-commit fails.

2022-07-14 07:51 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
> +    ```powershell
@macpijan

2022-09-12 21:45 UTC, merged