Stability tests doc
Dasharo/docs pull request #254
Opened 2022-07-25 13:38 UTC by PrzemyslawBanasiak13

2022-07-26 07:48 UTC, sulewskiprzemyslaw requested changes

2022-07-26 07:48 UTC, sulewskiprzemyslaw commented on mkdocs.yml
> +              - 'Stability': unified-test-documentation/dasharo-performance/404-stability.md
@PrzemyslawBanasiak13 These tests are prepared for the specific platform, so please add also a link in the test matrix.

2022-07-26 07:48 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/404-stability.md
> +This test aims to verify that DUT booted to firmware will not reboot during
Firmware? Or maybe Ubuntu?

2022-07-26 07:48 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/404-stability.md
> +# Dasharo Performance: Stability
```suggestion
# Dasharo Performance: Platform stability
```

2022-07-26 07:48 UTC, sulewskiprzemyslaw commented on mkdocs.yml
> +              - 'Stability': unified-test-documentation/dasharo-performance/404-stability.md
```suggestion
              - 'Platform stability': unified-test-documentation/dasharo-performance/404-stability.md
```

2022-07-26 13:19 UTC, PrzemyslawBanasiak13 commented on docs/unified-test-documentation/dasharo-performance/404-stability.md
> +This test aims to verify that DUT booted to firmware will not reboot during
Fixed

2022-07-28 09:30 UTC, sulewskiprzemyslaw approved these changes

2022-07-28 09:30 UTC, merged