add tests for fan speed
Dasharo/docs pull request #276
Opened 2022-08-17 14:50 UTC by PrzemyslawBanasiak13

Signed-off-by: pbanasiak <przemyslaw.banasiak@3mdeb.com>

2022-08-17 15:16 UTC, sulewskiprzemyslaw requested changes

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +# Dasharo Performance: Fan Control
@PrzemyslawBanasiak13 please add new position to `mkdocs` file. Without this the test suite will remain hidden.

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +
@PrzemyslawBanasiak13 please add this new test suite to the `test-matrix` dedicated for ASUS KGPE D-16.

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +This test aims to verify that fan is not stuck at initial frequency after
Are we sure that this test is about stucking the fan on initial frequency?

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +coldboot
```suggestion
coldboot.
```

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +1. Check if package `lm-sensors` is installed and if not, use bellow command in
Maybe it will be a better option to add `lm-sensors` package checking to the test setup section

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +This test aims to verify that fan is not stuck at initial frequency after
Are we sure that this test is about stucking the fan on initial frequency?

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +warmboot
```suggestion
warmboot.
```

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +reboot
```suggestion
reboot.
```

2022-08-17 15:16 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-performance/405-fan-control.md
> +This test aims to verify that fan is not stuck at initial frequency after
Are we sure that this test is about stucking the fan on initial frequency?

2022-08-23 10:44 UTC, Pokisiekk approved these changes

2022-08-23 11:43 UTC, sulewskiprzemyslaw approved these changes

2022-08-23 11:43 UTC, merged