protectli_vp46xx/firmware-update.md: add information about versions newer than 1.0.18
Dasharo/docs pull request #418
Opened 2022-12-15 14:29 UTC by sulewskiprzemyslaw

Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>

2022-12-20 08:10 UTC, miczyg1 requested changes

2022-12-20 08:10 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +## Updating to Dasharo v1.0.18 or newer versions
if one updates from v1.0.18 to v1.0.19 flashing only WP_RO and RW_SECTION_A is sufficient. BUt if v1.0.19 is goign to be the first Dasahro version being installed, full flashing is needed

2022-12-20 12:37 UTC, miczyg1 requested changes

2022-12-20 12:37 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +If the current version of the firmware on the device is older than v1.0.18 the
```suggestion
If the current version of the firmware on the device is older than v1.0.18 or
you are migrating from proprietary firmawre the
```

2022-12-20 13:12 UTC, miczyg1 requested changes

2022-12-20 13:12 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +be updated to v1.0.19, only the `WP_RO` and `RW_SECTION_A` should be flashed.
Forgot to mention that the Dasahro BIOS Boot medium lock must be disabled beforehand...

2022-12-20 13:12 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +you are migrating from proprietary firmware the whole flash chip should be
Proprietary firmware also need to disable `BIOS Lock` first

2022-12-21 08:10 UTC, miczyg1 requested changes

2022-12-21 08:10 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +Before starting the update procedure be sure to disable Dasahro BIOS Boot medium
```suggestion
Before starting the update procedure be sure to disable Dasharo BIOS Boot medium
```

2022-12-21 08:10 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +lock:
```suggestion
lock (if you already installed Dasharo and want to update):
```

2022-12-21 08:10 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/firmware-update.md
> +
We need the procedure for AMI BIOS too.

2022-12-22 10:03 UTC, sulewskiprzemyslaw commented
@miczyg1 in the first section I just added a reference to the Initial deployment documentation ("If your device is currently flashed with the proprietary firmware please refer to Initial deployment documentation.").

In my opinion, that reference resolves the problems described in the last requests.

2022-12-22 10:41 UTC, miczyg1 approved these changes

2022-12-22 10:41 UTC, merged