simplify recovery docs for beginners
Dasharo/docs pull request #468
Opened 2023-02-08 08:10 UTC by nedpfeiffer

As a relatively new and inexperienced Linux user, I found this recovery documentation pretty confusing. Adding a clarifying sentence to the introduction and moving around paragraphs helps simplify things. Per the Dasharo [documentation guidelines](https://docs.dasharo.com/dev-proc/documentation-guidelines/) the most important information should be at the top of the document; as such, I moved the section on the MSI Flash BIOS Button to the bottom considering it does not currently work.

If this article is more oriented towards developers it may not need any edits. Let me know what you think, thanks!

2023-02-08 09:48 UTC, miczyg1 commented
> If this article is more oriented towards developers it may not need any edits. Let me know what you think, thanks!

Of course the documentation is mainly for the community, not developers. Thank you for contributing!

2023-02-08 09:51 UTC, miczyg1 requested changes

2023-02-08 09:51 UTC, miczyg1 commented on docs/variants/msi_z690/recovery.md
> +There are two documented recovery methods: using a CH341A programming kit or using an external programmar like an [RTE](https://3mdeb.com/open-source-hardware/#rte).
We wrap the documentation on 80 characters (except markdown syntax like links)
```suggestion
There are two documented recovery methods: using a CH341A programming kit or
using an external programmar like an [RTE](https://3mdeb.com/open-source-hardware/#rte).
```

2023-02-08 09:53 UTC, pietrushnic commented
@nedpfeiffer please note [pre-commit checks fail](https://results.pre-commit.ci/run/github/316342881/1675843835.c8hUl7OOQhOXiHtsyZ4Q_A) for your PR. Please check [pre-commit](https://github.com/Dasharo/docs#pre-commit-hooks) section in README.

2023-02-09 20:44 UTC, nedpfeiffer commented
This PR was kind of a mess, I'm going to close it and split it into smaller parts. Apologies.

2023-02-09 20:44 UTC, closed without merging

2023-02-09 21:52 UTC, pietrushnic commented
@nedpfeiffer sure. Thank you for your effort and we looking for improved series.