Kgpe test description
Dasharo/docs pull request #50
Opened 2021-12-15 08:37 UTC by kl3mdeb

2021-12-15 10:00 UTC, sulewskiprzemyslaw requested changes

2021-12-15 10:00 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +operating system after coldboot.
In the test case desription we should add information, that the test case may be re-done several times to specify the platform and connection stability.

2021-12-15 10:00 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +This test aims to verify that the DUT properly detects USB device and boots into
In the test case desription we should add information, that the test case may be re-done several times to specify the platform and connection stability.

2021-12-15 10:00 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +This test aims to verify that the DUT properly detects USB device and boots into
In the test case description we should add information, that the test case may be re-done several times to specify the platform and connection stability.

2021-12-15 11:00 UTC, kl3mdeb commented
Added improvements.

2021-12-17 11:03 UTC, sulewskiprzemyslaw requested changes

2021-12-17 11:03 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-security/tpm-support.md
> +1.  For TPM1.2 - Execute command:
@kl3mdeb take a look at the numeration, please

2021-12-17 11:59 UTC, sulewskiprzemyslaw requested changes

2021-12-17 11:59 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +This test aims to verify that the DUT properly detects USB device and boots into
We should rewrite description like in USB test cases

2021-12-17 11:59 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +the operating system after warmboot. In this test case powering on/off is done
We should rewrite description like in USB test cases

2021-12-17 11:59 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +done by RTE relay. This test case may be re-done several times to specify the
We should rewrite description like in USB test cases

2021-12-17 11:59 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-detect.md
> +1. Power off the DUT.
We should replace in the Test steps section the following statements: Power On/Off to Power cutting On/Off.

2021-12-17 11:59 UTC, sulewskiprzemyslaw commented on docs/variants/asus_kgpe_d16/dasharo-compatibility/usb-boot.md
> +1. Power off the DUT.
We should replace in the Test steps section the following statements: Power On/Off to Power cutting On/Off.

2021-12-17 12:20 UTC, kl3mdeb commented
Just added improvements to usb-boot and usb-detect descriptions

2021-12-17 12:26 UTC, sulewskiprzemyslaw approved these changes

2021-12-17 12:28 UTC, sulewskiprzemyslaw approved these changes

2021-12-17 12:33 UTC, merged