[WIP] dasharo-compatibility-test-specification
Dasharo/docs pull request #54
Opened 2021-12-21 15:14 UTC by sulewskiprzemyslaw

Signed-off-by: Przemyslaw Sulewski przemyslaw.sulewski@3mdeb.com

2021-12-21 15:37 UTC, artur-rs commented
@pietrushnic this is initial approach to describe/gather unified tests specification in the Dasharo ecosystem.

Our questions:
1. Files structure - maybe you have another vision where wew should add those docs
2. Test matrix: which parameter is best suited to categorize the tests
  * processors
  * architectures
  * vendor platform name / code name, like apu1
  * dasharo product lines, like Dasharo Workstation

2021-12-22 11:35 UTC, pietrushnic commented
Feel free to reuse text that I will write below. I think we should start gather vision of Dasharo in once place and eliminate already outdated concepts.

First thing, SKU, flavors and modules are rather outdated concepts from the beginning phase of the project. Despite that I like division of tests by module, suite and case. Recent Dasharo releases show what customers and community want and those are features, if features are validated then things look good. Test results are not only for us Open Source Firmware Vendor, but also for developers who wants to use code, and end users who want to decide about which version of firmware they want to use.

We should distinguish features by:
* availability - available in upstream open source ecosystem or only in Dasharo, there may be also partial situation, where upstream for various reasons is not fully functional out of the box and additional action by user is needed
* support level - not all features can be validated everywhere, some are visible only on firmware level, some are visible on OS level and some are visible on both levels

![other_support](https://user-images.githubusercontent.com/1071894/147084837-cfa57c1c-9ca0-42fa-b214-171d67acbaee.png)

To answer questions:
1. Documentation always can be changed, so let's focus on content rather then structure. Good structure need time to mature
2. This is relate to above description - what given community group needs? Tests should be presented as easy for users as possible. What users care? Initial deployment (aka Installation manual) - what deployment method works for my platform, firmware update - how to update my firmware, recovery (de-bricking) - how to recover my platform, on what systems I can perform those operation and how, if there was stock BIOS can I safely recover to it - those are probably tests to cover in Dasharo flashing module, which should be renamed to something more aligned.

I know we have tests that prove intermediate steps, and it is ok to present results of those, but most important for end users is overall if given feature works, so we should have some simplified view of things.

Please let me know if it answer your questions.

2021-12-22 11:41 UTC, pietrushnic requested changes
I didn't finished the review since there is some background information that have to be explained offline.

2021-12-22 11:41 UTC, pietrushnic commented on docs/dasharo-compatibility-specification/dasharo-compatibility-specification.md
> +[link](https://docs.google.com/spreadsheets/d/1MPbz8OIDuuErZOHdnkxZnUo4snLptQU_mBKat3H2Mow/edit?usp=sharing).
Many privacy-conscious users will dislike presenting things in google docs. Also coreboot is always written with small letters :angry:

2021-12-22 11:41 UTC, pietrushnic commented on docs/dasharo-compatibility-specification/dasharo-compatibility-specification.md
> +Its main tasks are:
Please explain what is the goal of this document in clear and concise way.

2021-12-22 11:41 UTC, pietrushnic commented on docs/dasharo-compatibility-specification/dasharo-compatibility-specification.md
> +    stage acceptance criteria,
```suggestion
  stage acceptance criteria,
```

line wrapping here and in below is incorrect please fix that

2022-02-27 00:12 UTC, pietrushnic commented
@artur-rs @sulewskiprzemyslaw when we can get back to discussion here?

2022-03-01 16:40 UTC, pietrushnic commented
@artur-rs @sulewskiprzemyslaw ping2

2022-03-03 21:24 UTC, artur-rs commented
@sulewskiprzemyslaw please address the review comments. Piotr answered our initial concerns, in my opinion you can continue with the updates

2022-03-04 12:15 UTC, sulewskiprzemyslaw commented
@pietrushnic @artur-rs to this topic I will return on Monday, the 7th of march. In addition to making the appropriate corrections I will also do the following things:
- resolve all conflicts,
- add test documentation from the laptops testing (cc @macpijan).

2022-03-31 15:14 UTC, closed without merging