[draft] Protectli PTx01 test & hardware matrix
Dasharo/docs pull request #596
Opened 2023-06-23 13:32 UTC by sulewskiprzemyslaw

Signed-off-by: Przemyslaw Sulewski <przemyslaw.sulewski@3mdeb.com>

2023-06-28 13:15 UTC, miczyg1 requested changes

2023-06-29 06:33 UTC, sulewskiprzemyslaw commented on docs/variants/protectli_ptx01/hardware-matrix.md
> +| **Ethernet controller**        | 2x intel i225 (on-board)                    |
improved in 26490ebf4193cd182621ffdb07ea17a9578f17d0

2023-06-29 06:39 UTC, sulewskiprzemyslaw commented on docs/variants/protectli_ptx01/test-matrix.md
> +| 1.   | [Memory HCL][HCL]                     | HCL           | All                                  |
improved in e1518d70e96e011449816ce4df3c81a35c705a36

2023-06-29 06:39 UTC, sulewskiprzemyslaw commented on docs/variants/protectli_ptx01/test-matrix.md
> +| 10.  | [USB-C/Thunderbolt][UTC]              | UTC           | UTC004.001, UTC004.002               |
improved in e1518d70e96e011449816ce4df3c81a35c705a36

2023-06-29 06:39 UTC, sulewskiprzemyslaw commented on docs/variants/protectli_ptx01/test-matrix.md
> +
improved in e1518d70e96e011449816ce4df3c81a35c705a36

2023-06-29 07:30 UTC, miczyg1 commented
LGTM for starters

2023-06-29 10:50 UTC, merged