Msi unified docs
Dasharo/docs pull request #624
Opened 2023-07-28 13:31 UTC by miczyg1

2023-07-28 13:31 UTC, miczyg1 commented
Basically, it is sufficient to review only this commit: https://github.com/Dasharo/docs/pull/624/commits/fb06de89faa29fed5e386faf4d0b14853dfbf348

2023-07-31 08:44 UTC, miczyg1 commented
The comments do not appear if I paste just the commit hash, maybe when I link to commit from PR it will be different: https://github.com/Dasharo/docs/pull/624/commits/e31d499c3b2bd6fe02b524c0f0dafdaeda3d5d36

2023-08-01 13:18 UTC, mkopec requested changes

2023-08-01 13:47 UTC, miczyg1 commented on docs/unified/msi/hcl.md
> +    * Bandwidth: GPU's bandwidth.
@mkopec sometimes bandwidth is expressed in PCIe link width and sometimes in GB/s, dunno if it is memory or PCIe bandwidth of all the links...

2023-08-01 13:56 UTC, miczyg1 commented on docs/unified/msi/hcl.md
> +    | MSI GeForce RTX 3060 GAMING Z TRIO LHR | 12 GB     | GDDR6  | x16   | Gen4      | 1                         | |
```suggestion
    | MSI Radeon RX 6500 XT MECH 2X 4G OC | 4 GB     | GDDR6  | 180GB/s   | Gen4      | 1                         | Works only on Dasharo v1.1.0 or newer |
    | MSI GeForce RTX 3060 GAMING Z TRIO LHR | 12 GB     | GDDR6  | 358GB/s   | Gen4      | 1                         | |
```

2023-08-01 13:57 UTC, miczyg1 commented on docs/unified/msi/hcl.md
> +    * Bandwidth: GPU's bandwidth.
We will also need this fix: https://github.com/Dasharo/docs/pull/624/files#r1280687832

2023-08-01 13:57 UTC, mkopec commented on docs/unified/msi/hcl.md
> +    * Bandwidth: GPU's bandwidth.
Ah, just noticed the x16 and x4 below. Those are PCIe links indeed. But the values expressed in GB/s match these cards' memory bandwidth specs.

Doesn't really make sense to keep these in the same column.

2023-08-01 13:58 UTC, mkopec commented on docs/unified/msi/hcl.md
> +    * Bandwidth: GPU's bandwidth.
Thanks

2023-08-01 13:59 UTC, mkopec approved these changes

2023-08-01 14:38 UTC, macpijan approved these changes

2023-08-01 14:38 UTC, merged