docs/variants/msi_zx90/hardware-matrix.md: add wifi card
Dasharo/docs pull request #743
Opened 2024-01-19 12:47 UTC by filipleple

2024-01-22 14:21 UTC, miczyg1 requested changes

2024-01-22 14:55 UTC, filipleple commented on docs/variants/msi_z790/hardware-matrix.md
> +| **Wireless card**              | Intel Wi-Fi 6E AX210                        |
[Removed](https://github.com/Dasharo/docs/compare/ef18ec9e9c442ca00ce58c19bef09299fdd01e1d..9f0cca7a8ece790240bfac5c318417135013929f)

2024-01-22 15:17 UTC, macpijan approved these changes

2024-01-23 15:06 UTC, miczyg1 approved these changes

2024-01-23 15:06 UTC, merged