Vp2410/rel v1.1.0
Dasharo/docs pull request #766
Opened 2024-02-27 14:31 UTC by miczyg1

2024-02-28 13:23 UTC, miczyg1 commented
> @miczyg1 can you fix or comment on the CI errors?

One copy-pasted paragraph in openness_score.md which is obsolete, removed: 756d3da7889f5d0152fcdf7c38fc5b8cd3899c2b

Broken link to GLK FSP (bug in templates, fixed in the templates), updated: be56759560516eb297cc36cad3ca00a14d4cd9a3

For the rest of broken links, I have no idea, didn't touch them.

2024-02-29 10:20 UTC, mkopec approved these changes

2024-02-29 10:20 UTC, mkopec commented
Links appear to all be working now

2024-05-16 11:16 UTC, BeataZdunczyk requested changes

2024-05-16 11:16 UTC, BeataZdunczyk commented on docs/variants/protectli_vp2410/releases.md
> +## v1.1.0 - 2024-04-09
```suggestion
## v1.1.0 - 2024-05-16
```

2024-05-16 13:38 UTC, mkopec commented
Rebased, updated the release date and updated the openness score pngs. @BeataZdunczyk

2024-05-16 13:59 UTC, BeataZdunczyk requested changes
@mkopec Link to the Test Results needs updating to https://docs.google.com/spreadsheets/d/1wSE6xA3K3nXewwLn5lV39_2wZL1kg5AkGb4mvmG3bwE/edit#gid=1033426620

2024-05-16 14:20 UTC, mkopec commented
@BeataZdunczyk fixed

2024-05-16 14:22 UTC, merged