transparent-validation/novacustom: add assembly guide
Dasharo/docs pull request #809
Opened 2024-04-23 12:27 UTC by mkopec

2024-04-24 10:05 UTC, miczyg1 approved these changes

2024-04-24 10:07 UTC, miczyg1 requested changes
The image links probably should not have `../`

2024-04-24 10:53 UTC, mkopec commented
@miczyg1 removed in https://github.com/Dasharo/docs/pull/809/commits/46af47d21c5a13b1d9e0b46b08fdd761ed391e53

2024-04-26 17:12 UTC, pkubaj approved these changes

2024-05-06 09:34 UTC, miczyg1 approved these changes

2024-05-06 09:34 UTC, merged