docs/variants: update Protectli documentation
Dasharo/docs pull request #810
Opened 2024-04-23 13:41 UTC by arturkow2

Update documentation about Intel ME status. Add note to each platform which has Intel ME disabled.

2024-04-24 09:49 UTC, miczyg1 commented
LGTM, we only need the links to be in place.

2024-08-13 09:21 UTC, miczyg1 requested changes

2024-08-13 09:21 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/releases.md
> +- ME is now disabled by default ([ME soft-disable]((../../osf-trivia-list/me.md#soft-disabling-me)))
```suggestion
- ME is now disabled by default ([ME soft-disable](../../osf-trivia-list/me.md#soft-disabling-me))
```

One pair of parentheses extra

2024-08-13 09:21 UTC, miczyg1 commented on docs/variants/protectli_vp46xx/overview.md
>    [Intel FSP repo for details](https://github.com/intel/FSP/tree/master/CometLakeFspBinPkg#differentiating-cometlake1-and-cometlake2)))
```suggestion
  [Intel FSP repo for details](https://github.com/intel/FSP/tree/master/CometLakeFspBinPkg#differentiating-cometlake1-and-cometlake2))
```

Same here, although it is old code

2024-09-03 17:24 UTC, macpijan approved these changes

2024-09-03 17:25 UTC, macpijan approved these changes

2024-09-03 17:29 UTC, merged