Docs.dasharo update - OS versioning removal
Dasharo/docs pull request #828
Opened 2024-06-05 07:21 UTC by JanPrusinowski

Docs.dasharo update - OS versioning removal

2024-06-11 08:29 UTC, BeataZdunczyk commented on docs/unified-test-documentation/dasharo-stability/C04-power-management.md
> +## SPM006.002 2x warmboot cycle (AC)
We shouldn't remove all information about the OSs. We should leave information about the OS (Ubuntu/Windows), but remove the versioning.
> Is it always the case? Should we document this in a place where we explain which OSes are tested?

We could check. I'd just leave the OS type in the test name (in parentheses) for now.

2024-06-17 12:07 UTC, JanPrusinowski commented on docs/unified-test-documentation/dasharo-stability/C04-power-management.md
> +## SPM006.002 2x warmboot cycle (AC)
changed in: 5dabc6684fd90248cc71882565b562e1bf48f0cb

2024-06-17 12:38 UTC, BeataZdunczyk requested changes

2024-06-17 12:38 UTC, BeataZdunczyk commented on docs/unified-test-documentation/overview.md
> +(as of 17 june 2024)
```suggestion
(as of 17 June 2024)

2024-06-17 12:38 UTC, BeataZdunczyk commented on docs/unified-test-documentation/overview.md
> +`* unless specified otherwise in the test`
```suggestion
`* Unless specified otherwise in the test`

2024-06-28 15:32 UTC, macpijan approved these changes

2024-06-28 15:32 UTC, merged