docs/variants: Modify/Add links to results on osfv-test-results at gh
Dasharo/docs pull request #850
Opened 2024-07-03 06:57 UTC by philipandag

2024-07-03 12:10 UTC, philipandag commented
pre-commit.ci autofix

2024-07-11 09:20 UTC, mkopec requested changes
Looks good apart for 2 typos ;)

2024-07-11 09:20 UTC, mkopec commented on docs/variants/msi_z690/releases.md
> +[here](https://github.com/Dasharo/osfv-results/tree/main/boards/NovaCumsistom/ms7d25/results.csv).
```suggestion
[here](https://github.com/Dasharo/osfv-results/tree/main/boards/msi/ms7d25/results.csv).
```

2024-07-11 09:20 UTC, mkopec commented on docs/variants/msi_z790/releases.md
> +[here](https://github.com/Dasharo/osfv-results/tree/main/boards/NovaCumsistom/ms7e06/results.csv).
```suggestion
[here](https://github.com/Dasharo/osfv-results/tree/main/boards/msi/ms7e06/results.csv).
```

2024-07-16 05:18 UTC, philipandag commented
Thanks for finding those errors. Interesing that I wrote `msi` inside `NovaCustom` and didn't notice that the result doesn't resemble what i wrote :)

2024-07-16 09:24 UTC, mkopec approved these changes

2024-07-16 09:26 UTC, merged