docs/variants/dell_optiplex/hardware-matrix.md: add hardware specs
Dasharo/docs pull request #896
Opened 2024-09-11 13:41 UTC by wiktormowinski

2024-09-11 13:52 UTC, filipleple approved these changes

2024-09-11 13:55 UTC, filipleple requested changes

2024-09-11 13:55 UTC, filipleple commented on docs/variants/dell_optiplex/hardware-matrix.md
>  | **Attached devices**           | 1. TBD USB stick                                        |
`| **Attached devices**           | None                                     |` 
would make more sense IMHO

2024-09-12 07:47 UTC, wiktormowinski commented on docs/variants/dell_optiplex/hardware-matrix.md
>  | **Attached devices**           | 1. TBD USB stick                                        |
https://github.com/Dasharo/docs/pull/896/commits/cb81c8f6cb88840a8023fbff3a903256b1630285 sure

2024-09-12 09:13 UTC, filipleple approved these changes

2024-09-12 09:14 UTC, merged