Unified test documentation: embedded controller test suite
Dasharo/docs pull request #92
Opened 2022-03-14 11:39 UTC by sulewskiprzemyslaw

Signed-off-by: Przemysław Sulewski <przemyslaw.sulewski@3mdeb.com>

2022-03-14 14:16 UTC, damiankaras requested changes

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Power on the DUT and press the `BIOS_SETUP_KEY` to enter the setup menu
```suggestion
1. Power on the DUT and press the `BIOS_SETUP_KEY` to enter the setup menu.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   completely inoperable)
```suggestion
   completely inoperable).
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   completely inoperable)
```suggestion
   completely inoperable).
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey again should reactivate the touchpad
```suggestion
1. Pressing the hotkey again should reactivate the touchpad.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the display on/off hotkey once and note the effect
```suggestion
1. Press the display on/off hotkey once and note the effect.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press any key on the keyboard and note the effect
```suggestion
1. Press any key on the keyboard and note the effect.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey once should turn the internal LCD panel off
```suggestion
1. Pressing the hotkey once should turn the internal LCD panel off.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing any key on the keyboard should power the internal LCD panel back on
```suggestion
1. Pressing any key on the keyboard should power the internal LCD panel back on.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey once should mute the device
```suggestion
1. Pressing the hotkey once should mute the device.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey again should reenable the sound
```suggestion
1. Pressing the hotkey again should reenable the sound.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   of the screen
```suggestion
   of the screen.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Run `sudo libinput debug-events --show-keycodes` in the terminal
```suggestion
1. Run `sudo libinput debug-events --show-keycodes` in the terminal.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the display switch hotkey once and note the effect
```suggestion
1. Press the display switch hotkey once and note the effect.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   device disappear from the output of `lsusb`
```suggestion
   device disappear from the output of `lsusb`.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey again should make the USB device reappear
```suggestion
1. Pressing the hotkey again should make the USB device reappear.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Locate and open the power menu in the upper right corner of the screen
```suggestion
1. Locate and open the power menu in the upper right corner of the screen.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Enter Settings and navigate to the Wi-Fi panel
```suggestion
1. Enter Settings and navigate to the Wi-Fi panel.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Note the current state of the Airplane Mode switch
```suggestion
1. Note the current state of the Airplane Mode switch.
```

2022-03-14 14:16 UTC, damiankaras commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the flight mode hotkey twice and note the result of each keypress
```suggestion
1. Press the flight mode hotkey twice and note the result of each keypress.
```

2022-03-15 13:03 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Power on the DUT and press the `BIOS_SETUP_KEY` to enter the setup menu
Improved

2022-03-15 13:03 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Use the arrow keys and the Enter key to navigate the menus
Improved

2022-03-15 13:04 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey again should make the USB device reappear
Improved

2022-03-15 13:05 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the flight mode hotkey twice and note the result of each keypress
Improved

2022-03-15 13:06 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Run `sudo libinput debug-events --show-keycodes` in the terminal
Improved

2022-03-15 13:06 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Verify that pressing the play/pause key generates a `KEY_PLAYPAUSE` event
Improved

2022-03-15 13:07 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the cooling mode hotkey (Fn + 1) once and note the effect
Improved

2022-03-15 13:08 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the cooling mode hotkey once again and note the effect
Improved

2022-03-15 13:08 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   spin up to their maximum speed)
Improved

2022-03-15 13:08 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the cooling mode hotkey once again and note the effect
Improved

2022-03-15 13:08 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   spin up to their maximum speed)
Improved

2022-03-15 13:08 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +   return to normal)
Improved

2022-03-15 13:09 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Pressing the hotkey again should reactivate the touchpad
Improved

2022-03-15 13:10 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press the display on/off hotkey once and note the effect
Improved

2022-03-15 13:10 UTC, sulewskiprzemyslaw commented on docs/unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
> +1. Press any key on the keyboard and note the effect
Improved

2022-03-15 13:49 UTC, merged