docs/variants/msi: Update release notes
Dasharo/docs pull request #952
Opened 2024-12-02 10:33 UTC by miczyg1

For some reason outdated release notes got merged

2024-12-02 10:44 UTC, SergiiDmytruk commented on docs/variants/msi_z690/releases.md
> +instructions in [Dasharo release signature verification](/guides/signature-verification)
I think mkdocs likes prefers relative links.

2024-12-02 11:49 UTC, BeataZdunczyk requested changes

2024-12-02 11:49 UTC, BeataZdunczyk commented on docs/variants/msi_z690/releases.md
> +## v1.1.4 - 2024-11-26
date will need to be updated

2024-12-10 13:33 UTC, miczyg1 commented
ucode revision and date fixed in https://github.com/Dasharo/docs/pull/958

2024-12-10 13:33 UTC, closed without merging